server:
  port: 8888

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbname: chat
  charset: utf8mb4

mongo:
  uri: 666mongodb+srv://root:root@chat-mongo.rimufll.mongodb.net/?retryWrites=true&w=majority&appName=chat-mongo
  dbname: chat

elasticsearch:
  address: https://4ff4cca5c85e41169f6e3fc0ce869900.ap-east-1.aws.elastic-cloud.com:443
  api_key: SndVaUY1Y0JNMVVNVmZZQ1JFd0s6WlYtZkNfS3dMc2hFbVBMZUJmUnhMdw==
  insecure_skip_verify: true

redis:
  address: "localhost:6379"
  username: "root"
  password: "root"         
  db: 0

logger:
  level: info
  output: stdout
  format: json
  source_path: true
