definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: 2912528586@qq.com
    name: 汤新康
    url: http://www.example.com/support
  description: 聊天服务器API文档
  termsOfService: http://swagger.io/terms/
  title: Chat Server API接口文档
  version: "1.0"
paths:
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 创建新用户账号
      parameters:
      - description: 用户注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: 用户注册
      tags:
      - User
  /user/test:
    get:
      consumes:
      - application/json
      description: 测试接口，返回一些示例数据
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      summary: 测试接口
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: '请在此输入Bearer令牌，格式为: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
